name = "idea-leads-hub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[build]
command = "pnpm install --no-frozen-lockfile && npm run build"
cwd = "./"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"