name = "idea-leads-hub-1"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://xsqyftoblnsjkavhldcm.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcXlmdG9ibG5zamthdmhsZGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNTUwNjgsImV4cCI6MjA5MzgzMTA2OH0.oyk3NACBGUuDdfJDmWnSVo2V5iESE3CXRrzvRrPtUm0"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yIPrIzSpveyYkJpdbFsdsg_ofYGRzag"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1