export enum ActivityType {
  CALL = 'CALL',
  MEETING = 'MEETING',
  FOLLOW_UP = 'FOLLOW_UP',
  EMAIL = 'EMAIL',
  TASK = 'TASK',
  NOTE = 'NOTE',
  REMINDER = 'REMINDER',
  INVESTIGATION = 'INVESTIGATION',
  ACTION = 'ACTION',
  INSTAGRAM_MESSAGE = 'INSTAGRAM_MESSAGE'
}
